/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SuiButton {
        "type": string;
    }
    interface SuiDetailedRecordsIcon {
    }
    interface SuiFacebookIcon {
    }
    interface SuiFullyCustomizableIcon {
    }
    interface SuiLink {
        "href": string;
    }
    interface SuiPinterestIcon {
    }
    interface SuiStatisticsIcon {
    }
    interface SuiTwitterIcon {
    }
}
declare global {
    interface HTMLSuiButtonElement extends Components.SuiButton, HTMLStencilElement {
    }
    var HTMLSuiButtonElement: {
        prototype: HTMLSuiButtonElement;
        new (): HTMLSuiButtonElement;
    };
    interface HTMLSuiDetailedRecordsIconElement extends Components.SuiDetailedRecordsIcon, HTMLStencilElement {
    }
    var HTMLSuiDetailedRecordsIconElement: {
        prototype: HTMLSuiDetailedRecordsIconElement;
        new (): HTMLSuiDetailedRecordsIconElement;
    };
    interface HTMLSuiFacebookIconElement extends Components.SuiFacebookIcon, HTMLStencilElement {
    }
    var HTMLSuiFacebookIconElement: {
        prototype: HTMLSuiFacebookIconElement;
        new (): HTMLSuiFacebookIconElement;
    };
    interface HTMLSuiFullyCustomizableIconElement extends Components.SuiFullyCustomizableIcon, HTMLStencilElement {
    }
    var HTMLSuiFullyCustomizableIconElement: {
        prototype: HTMLSuiFullyCustomizableIconElement;
        new (): HTMLSuiFullyCustomizableIconElement;
    };
    interface HTMLSuiLinkElement extends Components.SuiLink, HTMLStencilElement {
    }
    var HTMLSuiLinkElement: {
        prototype: HTMLSuiLinkElement;
        new (): HTMLSuiLinkElement;
    };
    interface HTMLSuiPinterestIconElement extends Components.SuiPinterestIcon, HTMLStencilElement {
    }
    var HTMLSuiPinterestIconElement: {
        prototype: HTMLSuiPinterestIconElement;
        new (): HTMLSuiPinterestIconElement;
    };
    interface HTMLSuiStatisticsIconElement extends Components.SuiStatisticsIcon, HTMLStencilElement {
    }
    var HTMLSuiStatisticsIconElement: {
        prototype: HTMLSuiStatisticsIconElement;
        new (): HTMLSuiStatisticsIconElement;
    };
    interface HTMLSuiTwitterIconElement extends Components.SuiTwitterIcon, HTMLStencilElement {
    }
    var HTMLSuiTwitterIconElement: {
        prototype: HTMLSuiTwitterIconElement;
        new (): HTMLSuiTwitterIconElement;
    };
    interface HTMLElementTagNameMap {
        "sui-button": HTMLSuiButtonElement;
        "sui-detailed-records-icon": HTMLSuiDetailedRecordsIconElement;
        "sui-facebook-icon": HTMLSuiFacebookIconElement;
        "sui-fully-customizable-icon": HTMLSuiFullyCustomizableIconElement;
        "sui-link": HTMLSuiLinkElement;
        "sui-pinterest-icon": HTMLSuiPinterestIconElement;
        "sui-statistics-icon": HTMLSuiStatisticsIconElement;
        "sui-twitter-icon": HTMLSuiTwitterIconElement;
    }
}
declare namespace LocalJSX {
    interface SuiButton {
        "type"?: string;
    }
    interface SuiDetailedRecordsIcon {
    }
    interface SuiFacebookIcon {
    }
    interface SuiFullyCustomizableIcon {
    }
    interface SuiLink {
        "href"?: string;
    }
    interface SuiPinterestIcon {
    }
    interface SuiStatisticsIcon {
    }
    interface SuiTwitterIcon {
    }
    interface IntrinsicElements {
        "sui-button": SuiButton;
        "sui-detailed-records-icon": SuiDetailedRecordsIcon;
        "sui-facebook-icon": SuiFacebookIcon;
        "sui-fully-customizable-icon": SuiFullyCustomizableIcon;
        "sui-link": SuiLink;
        "sui-pinterest-icon": SuiPinterestIcon;
        "sui-statistics-icon": SuiStatisticsIcon;
        "sui-twitter-icon": SuiTwitterIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sui-button": LocalJSX.SuiButton & JSXBase.HTMLAttributes<HTMLSuiButtonElement>;
            "sui-detailed-records-icon": LocalJSX.SuiDetailedRecordsIcon & JSXBase.HTMLAttributes<HTMLSuiDetailedRecordsIconElement>;
            "sui-facebook-icon": LocalJSX.SuiFacebookIcon & JSXBase.HTMLAttributes<HTMLSuiFacebookIconElement>;
            "sui-fully-customizable-icon": LocalJSX.SuiFullyCustomizableIcon & JSXBase.HTMLAttributes<HTMLSuiFullyCustomizableIconElement>;
            "sui-link": LocalJSX.SuiLink & JSXBase.HTMLAttributes<HTMLSuiLinkElement>;
            "sui-pinterest-icon": LocalJSX.SuiPinterestIcon & JSXBase.HTMLAttributes<HTMLSuiPinterestIconElement>;
            "sui-statistics-icon": LocalJSX.SuiStatisticsIcon & JSXBase.HTMLAttributes<HTMLSuiStatisticsIconElement>;
            "sui-twitter-icon": LocalJSX.SuiTwitterIcon & JSXBase.HTMLAttributes<HTMLSuiTwitterIconElement>;
        }
    }
}
